blank_issues_enabled: false
contact_links:
  - name: Discord Bot Invite
    url: https://discord.com/api/oauth2/authorize?client_id=883446355656343562&permissions=8&scope=bot%20applications.commands
    about: If you wish to add the bot to your guilds, use this invite url to do so.
  - name: Grid Bot Moderation Guidelines
    url: https://grid-bot-stg.ops.vmminfra.net/moderation
    about: Please refer to here before opening Blacklist appeals.
  - name: Grid Bot Terms of Service
    url: https://grid-bot-stg.ops.vmminfra.net/legal/tos
    about: Please refer to here for the terms and conditions for using or integrating this bot within Discord.
  - name: Grid Bot Privacy Policy
    url: https://grid-bot-stg.ops.vmminfra.net/legal/privacy-policy
    about: Please refer to here for the information on how we use your data internally.
